// <auto-generated />
namespace COMP4900_SOCE_WebApp.Migrations.SensorMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedrequiredforeverythingexceptsensorvalueaddedsavedreportfinaldb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedrequiredforeverythingexceptsensorvalueaddedsavedreportfinaldb));
        
        string IMigrationMetadata.Id
        {
            get { return "201605182306578_Added required for everything except sensor value, added savedreport, final db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
