// <auto-generated />
namespace COMP4900_SOCE_WebApp.Migrations.SensorMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deleteddatetimetableandaddeddatetimevalueto9projecttables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteddatetimetableandaddeddatetimevalueto9projecttables));
        
        string IMigrationMetadata.Id
        {
            get { return "201605122225206_deleted datetime table and added datetime value to 9 project tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
