// <auto-generated />
namespace COMP4900_SOCE_WebApp.Migrations.SensorMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editedCustomGroupmodelandremovedUserGroupmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editedCustomGroupmodelandremovedUserGroupmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201605180016477_edited CustomGroup model and removed UserGroup model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
